source ~/.vim/plugins.vim
source ~/.vim/globals.vim
source ~/.vim/functions.vim
source ~/.vim/keybindings.vim
if !empty($VIM_COLOR)
        colorscheme $VIM_COLOR
    else
        colorscheme solarized
endif


nnoremap <silent> <tab> :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bnext<CR>
nnoremap <silent> <s-tab> :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bprevious<CR>

