export PATH=/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export EDITOR='vim'
export FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*}"'
export SDKMAN_DIR="$HOME/.sdkman"
export ZSH_THEME="powerlevel10k/powerlevel10k"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#475c61,bg=none"
export plugins=(git osx zsh-autosuggestions zsh-aliases-exa)
