if [[ -f ~/.zshrc.mac ]]; then
    source ~/.zshrc.mac;
fi
if [[ -f ~/.zsh.aliases ]]; then
    source ~/.zsh.aliases;
fi
source $ZSH/oh-my-zsh.sh
if [[ -f ~/.p10k.zsh ]]; then
    source ~/.p10k.zsh;
fi
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

{%@@ if profile == "coolmaster" @@%}
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
{%@@ endif @@%}
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
