# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle :compinstall filename '/Users/jonas/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
[[ -s ~/.zshrc.mac ]] && source ~/.zshrc.mac;
[[ -s ~/.zshrc.shared ]] && source ~/.zshrc.shared;
[[ -s ~/.zsh.aliases ]] && source ~/.zsh.aliases;
[[ -s $ZSH/oh-my-zsh.sh ]] && source $ZSH/oh-my-zsh.sh;
[[ -s ~/.p10k.zsh ]] && source ~/.p10k.zsh;
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
[[ -s ~/.fzf.zsh ]] && source ~/.fzf.zsh
[[ -s /usr/local/opt/findutils/libexec/gnubin ]] && export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"

# Unlimited history size.
export HISTSIZE=1000000
export HISTFILE="$HOME/.history"
# History won't be saved without the following command.
# The maximum number of history events to save in the history file.
export SAVEHIST=$HISTSIZE
# Ignore duplicates.
setopt hist_ignore_all_dups
# Ignore commands starting with space.
setopt hist_ignore_space



# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jonas/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jonas/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jonas/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jonas/google-cloud-sdk/completion.zsh.inc'; fi
